In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.arange(16).reshape(4,4))

In [3]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [5]:
permutation = np.random.permutation(4)
permutation

array([0, 2, 1, 3])

In [7]:
df.take(permutation)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7
3  12  13  14  15

In [8]:
box = np.array([1,2,3])

In [13]:
"""
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.randint.html
"""
shaker = np.random.randint(0,len(box),size=5)

In [14]:
shaker

array([2, 1, 1, 1, 0])

In [15]:
hand_grabs = box.take(shaker)

In [16]:
hand_grabs

array([3, 2, 2, 2, 1])